"""add approval_status to users

Revision ID: 0db7823c25c1
Revises: 97ae97d1c5ad
Create Date: 2026-08-18 12:44:55.026516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0db7823c25c1'
down_revision: Union[str, None] = '97ae97d1c5ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('approval_status', sa.String(length=20), server_default='approved', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'approval_status')
    # ### end Alembic commands ###
